version: "3.9"
services:

  people:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8080:8080"
    build: .
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "people"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    image: postgres:latest
    networks:
      - mynetwork

networks:
  mynetwork:
