performance:
  SpreadOperator:
    active: true

style:
  WildcardImport:
    active: true
  ReturnCount:
    active: false
    excludeGuardClauses: true
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
