name: Java CI/CD Workflow flow to ENTERPRISE 2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#          cache: gradle


      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.INFRAKEY}}
          command: |
            cd infraservice;

      - name: List files in source directory
        run: |
          ls -l infraservice;
          pwd;


#      - name: Shutdown Docker containers
#        run: docker-compose down

      - name: Copy repo to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.INFRAKEY }}
          source: "."
          target: "/infraservice"
          debug: true

#      - name: Build and run Docker containers on remote server
#        uses: D3rHase/ssh-command-action@v0.2.2
#        with:
#          host: ${{secrets.SSH_HOST}}
#          user: ${{secrets.SSH_USER}}
#          private_key: ${{secrets.INFRAKEY}}
#          command: |
#            cd /infraservice
#            docker-compose up --build -d

